# ------------------------------------------------------------------------------
# E3-DescriptivesInSlidingWindow.py
# Oct 16, 2020
# Hongyi Zheng
# Calculates values of a selected descriptive generated by a sliding window and
# return them as a numpy array.
# Accepts 1D/2D numpy array.
# ------------------------------------------------------------------------------

import numpy as np

writtenBy = "Hongyi Zheng"


def descriptivesInSlidingWindow(input, paramter_flag, window_size):
    if paramter_flag not in [1, 2, 3]:
        raise ValueError("Invalid Parameter Flag")
    if paramter_flag == 3:
        if len(input) != 2:
            raise ValueError("Requires 2D Object")
        n = len(input[0])
    else:
        n = len(input)
    if window_size > n or window_size < 1:
        raise ValueError("Invalid Window Size")
    result = np.empty(n - window_size + 1)
    for i in range(n - window_size + 1):
        if paramter_flag == 1:
            result[i] = np.mean(input[i:i + window_size])
        elif paramter_flag == 2:
            result[i] = np.std(input[i:i + window_size])
        else:
            result[i] = np.corrcoef(input[:, i:i + window_size])[0][1]
    return result
